from tkinter import *
from tkinter import StringVar
global srcvalue
def click(event):
    text = event.widget.cget("text")
    print(text)
    if text == "=":
        if srcvalue.get().isdigit():
            value = int(srcvalue.get())
        else:
            value = eval(screen.get())

        srcvalue.set(value)
        srcvalue.update()
    elif text == "C":
        srcvalue.set("")
        srcvalue.update()
    else:
        srcvalue.set(srcvalue.get() + text)
        srcvalue.update()
root = Tk()
root.geometry("630x850")
root.title("calculator By zaidi")

srcvalue = StringVar()
srcvalue.set("")
screen = Entry(root, textvar=srcvalue,font="lucida 40 bold")
screen.pack(fill=X, ipadx=8,pady=10,padx=10)
f= Frame(root, bg="black")
button = Button(f,text="C", padx=18,pady=18,font="lucida 35 bold")
button.bind("<Button-1>",click)
button.pack(side=LEFT,padx=12,pady=12)
button = Button(f,text="%", padx=28,pady=18,font="lucida 35 bold")
button.pack(side=LEFT,padx=12,pady=12)
button.bind("<Button-1>",click)
button = Button(f,text="C", padx=28,pady=18,font="lucida 35 bold")
button.pack(side=LEFT,padx=12,pady=12)
button.bind("<Button-1>",click)
button = Button(f,text="/", padx=28,pady=18,font="lucida 35 bold")
button.pack(side=LEFT,padx=12,pady=12)
button.bind("<Button-1>",click)
f.pack()


f= Frame(root, bg="black")
button = Button(f,text="7", padx=28,pady=18,font="lucida 35 bold")
button.bind("<Button-1>",click)
button.pack(side=LEFT,padx=13,pady=12)
button = Button(f,text="8", padx=28,pady=18,font="lucida 35 bold")
button.pack(side=LEFT,padx=12,pady=12)
button.bind("<Button-1>",click)
button = Button(f,text="9", padx=28,pady=18,font="lucida 35 bold")
button.pack(side=LEFT,padx=12,pady=12)
button.bind("<Button-1>",click)
button = Button(f,text="*", padx=28,pady=18,font="lucida 35 bold")
button.pack(side=LEFT,padx=12,pady=12)
button.bind("<Button-1>",click)
f.pack()

f= Frame(root, bg="black")
button = Button(f,text="4", padx=28,pady=18,font="lucida 35 bold")
button.bind("<Button-1>",click)
button.pack(side=LEFT,padx=12,pady=12)
button = Button(f,text="5", padx=28,pady=18,font="lucida 35 bold")
button.pack(side=LEFT,padx=12,pady=12)
button.bind("<Button-1>",click)
button = Button(f,text="6", padx=28,pady=18,font="lucida 35 bold")
button.pack(side=LEFT,padx=12,pady=12)
button.bind("<Button-1>",click)
button = Button(f,text="-", padx=28,pady=18,font="lucida 35 bold")
button.pack(side=LEFT,padx=12,pady=12)
button.bind("<Button-1>",click)
f.pack()

f= Frame(root, bg="black")
button = Button(f,text="1", padx=28,pady=18,font="lucida 35 bold")
button.bind("<Button-1>",click)
button.pack(side=LEFT,padx=12,pady=12)
button = Button(f,text="2", padx=28,pady=18,font="lucida 35 bold")
button.pack(side=LEFT,padx=12,pady=12)
button.bind("<Button-1>",click)
button = Button(f,text="3", padx=28,pady=18,font="lucida 35 bold")
button.pack(side=LEFT,padx=12,pady=12)
button.bind("<Button-1>",click)
button = Button(f,text="+", padx=28,pady=18,font="lucida 35 bold")
button.pack(side=LEFT,padx=12,pady=12)
button.bind("<Button-1>",click)
f.pack()

f= Frame(root, bg="black")
button = Button(f,text="00", padx=28,pady=18,font="lucida 35 bold")
button.bind("<Button-1>",click)
button.pack(side=LEFT,padx=12,pady=12)
button = Button(f,text="0", padx=28,pady=18,font="lucida 35 bold")
button.pack(side=LEFT,padx=12,pady=12)
button.bind("<Button-1>",click)
button = Button(f,text=".", padx=28,pady=18,font="lucida 35 bold")
button.pack(side=LEFT,padx=12,pady=12)
button.bind("<Button-1>",click)
button = Button(f,text="=", padx=28,pady=18,font="lucida 35 bold")
button.pack(side=LEFT,padx=12,pady=12)
button.bind("<Button-1>",click)
f.pack()
root.mainloop()